### ISSUE TITLE
Anybody takes over maintenance? REPO APPEARS INACTIVE

### ISSUE THREAD

**Issue by dalanicolai** [atykhonov/google-translate#106]
It seems the maintainer is inactive for this repo for almost a year now. The master branch does not seem to work well in the current state (see pull requests #103 #104).

Furthermore as spacemacs uses [this repository via MELPA](https://melpa.org/#/google-translate), the function also does not work well in spacemacs.

Therefore I am starting a discussion about future maintenance. Let's first ask:
Is someone able and willing to fork the repository and take over the maintenance?
(Unfortunately I am just learning emacs and emacs-lisp).

Or if someone already maintains a fork of this repo then please let us know here.
Thanks!

**Comment by stardiviner** [comment]
Check out the GitHub forks network, seems there are lot forks, and someone push some commits already.

https://github.com/atykhonov/google-translate/network

**Comment by dalanicolai** [comment]
Hi @stardiviner,
Thanks for your reply. I did not know about the forks network (nice to learn), but I found that @f279801 created a fork with several fixes. I have asked him if he was interested to become the new maintainer. Additionally, on May 21st I have emailed @atykhonov to ask him what he thinks about this. Unfortunately I got no response yet. Therefore, I suggest we direct the people to the @f279801 fork. I will ask @f279801 for confirmation once more and then post the definite link to the new, maintained, fork here.

**Comment by stardiviner** [comment]
We need find a maintainer at first, then use the maintainer's fork. And there is an alternative solution, let author add someone as collaborator. So those collaborator can merge PR. This is the better solution. And this repo is not active in 1 year, not really very long. So let's wait for author. And I will send an emial to author to ask about this too.

**Comment by stardiviner** [comment]
I asked the current maintainer, He added me as collaborator. I will merge some fixed now. For now, I think this issue can be closed. And any PR welcome. For simple PR, I will merge directlry. big PR I will invite Andrey Tykhonov to review.

**Comment by dalanicolai** [comment]
Great! Thanks you picked it up. Of course I did email the maintainer before and also opened this issue but there was no response. Anyway nice it is maintained again now...
