### ISSUE TITLE
somewhat unskillful in en->ja translation

### ISSUE THREAD

**Issue by yamaoka** [atykhonov/google-translate#133]
Hi,

First of all, thank you for a good Emacs program.　But I normally use `trans` [1] (with an Emacs interface) rather than google-translate for the English to Japanese translation because google-translate sometimes mis-recognizes transitive verb as intransitive verb.　For instance google-translate translates this sentense[2]

Use of a SET pin bypass capacitor also increases start-up time.

into

SETピンのバイパス・コンデンサの使用も増加して起動時間を。

In this case `increases` seems to be interpreted as an intransitive verb.　On the other hands, `trans` works good as follows:

$ echo "Use of a SET pin bypass capacitor also increases start-up time." | trans - en:ja

SETピンのバイパスコンデンサを使用すると、起動時間も長くなります。

I don't know what makes them differ but I hope google-translate works as it does.　Thanks in advance.

[1] https://git.io/trans
[2] https://www.analog.com/media/en/technical-documentation/data-sheets/LT3045.pdf

**Comment by kdmsnr** [comment]
I think #99 can solve this issue

**Comment by yamaoka** [comment]
Oh, it makes google-translate really great (at least on en>ja translation).　Thanks a lot!

**Comment by stardiviner** [comment]
Duplicated with #99, So closed.
