### ISSUE TITLE
[FEATURE] Make google-translate async

### ISSUE THREAD

**Issue by stardiviner** [atykhonov/google-translate#134]
I think google-translate should be able to be async, especially for some interfact which use google-translate as backend, or sometimes the network is not fast. Async can let user get better experiement.

**Comment by lorniu** [comment]
I implemented an asynchronous version based on this project. You can see if it helps.

[https://github.com/lorniu/go-translate](https://github.com/lorniu/go-translate)

**Comment by stardiviner** [comment]
@lorniu Thanks, I'm looking at your code. I used to check out google-translate. But implement async is big work for google-translate.

**Comment by lorniu** [comment]
@stardiviner At the beginning, I also wanted to add asynchronous support through PR or fork on the basis of this project. But I felt that the workload was a bit heavy.
That's why I wrote a new one. It uses a lot of code from this project, so, thank you very much.

**Comment by lol219** [comment]
Is there any reason why this repo is closed
