### ISSUE TITLE
google-translate--search-tkk: Search failed: ",tkk:'"

### ISSUE THREAD

**Issue by thjwong** [atykhonov/google-translate#138]
google-translate-version: 0.12.0
emacs: 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian

Tried also 
(setq google-translate-backend-method 'curl)
and
(setq google-translate-backend-method 'wget)
But doesn't help.

**Comment by suonlight** [comment]
I have the same issue with emacs 28 native-comp

**Comment by stardiviner** [comment]
Same with this issue. Closed
Check out this https://github.com/atykhonov/google-translate/issues/80#issuecomment-424822925
