### ISSUE TITLE
Package tls is deprecated

### ISSUE THREAD

**Issue by dodona2** [atykhonov/google-translate#139]
Contacting host: translate.google.com:80
Opening TLS connection to ‘translate.google.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/pki/tls/certs/ca-bundle.crt -p 443 translate.google.com’...done
Opening TLS connection to ‘translate.google.com’...done
google-translate--search-tkk: Search failed: ",tkk:'"
Package tls is deprecated

**Comment by stardiviner** [comment]
Same with this issue. Closed
Check out this https://github.com/atykhonov/google-translate/issues/80#issuecomment-424822925
