### ISSUE TITLE
Avoid blocking behaviour

### ISSUE THREAD

**Issue by moritzschaefer** [atykhonov/google-translate#150]
The default 'url-retrieve-synchronously' command is blocking emacs entirely if there is an issue with the network connection. Would it make sense to add a timeout to the command, or even implement asynchronous behaviour?

**Comment by stardiviner** [comment]
I proposed this async supporting before, but it's complicated to implement. Currently this project is in life maintain mode. But if you want to add this feature, PR is welcome.

About TIMEOUT is a solution. I add in the commit 3a1c7a6
