### ISSUE TITLE
Background color to clearly identify source and target blocks

### ISSUE THREAD

**Issue by svauban** [atykhonov/google-translate#25]
Hello, could it be possible to adjust the beginning and end of the source and target blocks so that we can give them a nice background face, and have them stand out?

To illustrate what I mean, take a look at http://screencast.com/t/OuAuQ3vYsr.

Best regards

**Comment by stardiviner** [comment]
@svauban Do you still have this problem? If did, can you debug it on your machine, I don't have Windows system available.

As this issue is not updated or any progress, so closed now. If have any update, re-open this issue.
