### ISSUE TITLE
Wrong type argument

### ISSUE THREAD

**Issue by fhaun** [atykhonov/google-translate#40]
With GNU Emacs 25.1.50.1 (armv7l-unknown-linux-gnueabihf, X toolkit, Xaw3d scroll bars) of 2015-12-26, I get:
Wrong type argument: integer-or-marker-p, 4294967295.0

Here is the backtrace. I hope this helps, Frank

Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p 4294967295.0)
  logand(413504475 4294967295.0)
  google-translate--gen-rl(403419 "+-a^+6")
  #[(a e) "\303	\\\n\"\207" [a e vb google-translate--gen-rl] 3](403318 101)
  cl-reduce(#[(a e) "\303	\\\n\"\207" [a e vb google-translate--gen-rl] 3] "enter" :initial-value 403318)
  google-translate--gen-tk("enter")
  google-translate--request("en" "de" "enter")
  google-translate-request("en" "de" "enter")
  google-translate-translate("en" "de" "enter")
  %google-translate-at-point(nil nil)
  google-translate-at-point(nil)
  funcall-interactively(google-translate-at-point nil)
  call-interactively(google-translate-at-point record nil)
  command-execute(google-translate-at-point record)
  execute-extended-command(nil "google-translate-at-point" nil)
  funcall-interactively(execute-extended-command nil "google-translate-at-point" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by momomo5717** [comment]
Hello, @fhaun

It seems `4294967295` was evaluated as a floating-point number.
https://github.com/atykhonov/google-translate/blob/master/google-translate-core.el#L179

Here is a quick fix for this issue:
https://gist.github.com/momomo5717/16df9af4ce044367487c
It would be helpful if you could try it.

I didn't realize that the minimum range of integer is 30 bits.
http://www.gnu.org/software/emacs/manual/html_node/elisp/Integer-Basics.html#Integer-Basics

Thank you.

**Comment by fhaun** [comment]
Hi momomo5717,

very nice, works fine now.

Thanks and regards, Frank

**Comment by atykhonov** [comment]
Hi all!

I've committed changes which I had found in the gist. The newest v0.11.4 contains these changes.

@momomo5717 thank you very much for contribution!

@momomo5717 could you please provide your name, surname and email? I would like to add you to the list of contributors.

Thank you!

**Comment by momomo5717** [comment]
@fhaun Thank you for the feedback! I'm glad it works for you.

@atykhonov Thank you for merging it!

>@momomo5717 could you please provide your name, surname and email? I would like to add you to the list of contributors.

If possible, could you add momomo5717([at]google[dot]com) ?

I'm happy I could contribute.
 
Thank you.

**Comment by atykhonov** [comment]
Hi @momomo5717 !

I'm very sorry for such long delay! I've added you to the list of Contributors (`README` and to the each `.el` file).

Thank you very much for the contribution!

**Comment by momomo5717** [comment]
Hi @atykhonov,

My pleasure :smile:
This is the first time I've been listed as a contributor.
Many thanks!

PS: I'm so sorry I made a typo at the previous post. I'm very embarrassed.
I use `gmail.com`.

I will send a PR.
I'm sorry for the trouble.

Thank you.
