### ISSUE TITLE
[Feature request] Add Input method auto toggling to Default UI

### ISSUE THREAD

**Issue by lislon** [atykhonov/google-translate#44]
Hi! 

What do you think about adding auto toggling feature in the Default UI like in Smooth UI?
I sticking to the Default UI, because I am able to use 4 separate keybindings for:
 * google-translate-query-translate-reverse
 * google-translate-query-translate        
 * google-translate-at-point-reverse       
 * google-translate-at-point

**Comment by atykhonov** [comment]
Hi!

I'm sorry for such long-long delay. I've just implemented it, and it is available in `default-ui-auto-toggling` branch. I need also to change documentation for that feature. Could you please let me know: do you still need this feature?

Thank you in advance!

**Comment by lislon** [comment]
Hello! 
I just  tested your branch and it's work like a charm! Would like to see it in master.
Thank you very much!  :heart:

**Comment by atykhonov** [comment]
Hi!

The feature is merged to the master. Use the latest `v0.11.13` version. Thank you for the feature request!
