### ISSUE TITLE
[Feature request] Listen to translation in target language

### ISSUE THREAD

**Issue by ackalker** [atykhonov/google-translate#46]
First off, thank you for creating this very useful package :-)

I like the ability to listen to the correct pronunciation a lot. I was a bit surprised to find that there is a listen button only for the source language. To listen to the pronunciation in the target language, which is very useful when translating into a foreign language, I now have to copy the translation, reverse the direction of the translation, translate again, then activate the listen button, which is a bit cumbersome.

Please consider adding a button to listen to the translation in target language also.

**Comment by atykhonov** [comment]
> I was a bit surprised to find that there is a listen button only for the source language

Ah, really, it is quite expected to have it! :-) I haven't even thought about such a feature before.

I've recently pushed the changes with the button. Please update `google-translate` (v0.11.7).

Thank  you for the feature request!

**Comment by ackalker** [comment]
You're welcome, and thank you so much for implementing it :-)
