### ISSUE TITLE
Fix [Listen] button url when using "auto" source

### ISSUE THREAD

**Issue by OGAWAHirofumi** [atykhonov/google-translate#59]
Hi,

If source language is "auto", it makes url has translate_tts?tl=auto. But translate_tts doesn't accpect
tl=auto, and returns 404 error or such.

So this fixes it by using auto detected language instead of "auto".

[patch file](https://github.com/atykhonov/google-translate/files/629074/listen-auto-fix.txt)

**Comment by atykhonov** [comment]
Thank you! Fixed in #61.
