### ISSUE TITLE
Add "hl" parameter by current-iso639-language (if nil, "en")

### ISSUE THREAD

**Issue by OGAWAHirofumi** [atykhonov/google-translate#64]
Now translate_s/single has "hl" parameter. It looks like set from
browser's Accept-Language setting.

This try to set it by emacs's current-iso639-language, however I'm not
sure whether improving translation or not.

[patch file](https://github.com/atykhonov/google-translate/files/635274/p3-set-current-language.txt)

**Comment by stardiviner** [comment]
I suggest a simpler workaround.

```diff
@@ -189,6 +194,7 @@ translate TEXT from SOURCE-LANGUAGE to T
     `(("client" . "t")
       ("ie"     . "UTF-8")
       ("oe"     . "UTF-8")
+      ("hl"     . ,(if current-iso639-language (symbol-name current-iso639-language) "en"))
       ("sl"     . ,source-language)
       ("tl"     . ,target-language)
       ("q"      . ,text)
```

WDYT?

**Comment by stardiviner** [comment]
And PR welcome.

**Comment by stardiviner** [comment]
I checked the variable `current-iso639-language` on my machine, it is `"en"`. What's the value on your machine?

**Comment by OGAWAHirofumi** [comment]
I'm setting japanese environment, so current-iso639-language is "ja" for me.

**Comment by stardiviner** [comment]
I see, Do you agree with my upper patch? if ok, I'm going to fix it. WDYT?

**Comment by OGAWAHirofumi** [comment]
Yes, I'm ok with your patch. Thanks
