### ISSUE TITLE
Add proxy support for google-translate service in Emacs

### ISSUE THREAD

**Issue by stardiviner** [atykhonov/google-translate#70]
In some countries, we need  to access Google services through proxy or other tools, can `google-translate` support proxy in Emacs?

**Comment by JianleiZhang** [comment]
```(setq url-proxy-services '("http" . "127.0.0.1:8123")))```
Be careful of DNS contamination if you live in China!

**Comment by mgcyung** [comment]
The http and https proxy should be both set
`(setq url-proxy-services '(("http" . "127.0.0.1:8123") 
                           ("https" . "127.0.0.1:8123")))`

**Comment by stardiviner** [comment]
I'm curious is it possible only let google-translate through the url-proxy-services? Or google-translate.el can pass proxy as argument to url-request function?

**Comment by mgcyung** [comment]
Try 
```
(setq url-proxy-services '(("http" . "127.0.0.1:8123")
                           ("https" . "127.0.0.1:8123")
                           ("no_proxy" . "^.*(?!translate\\.google\\.com).*$")))
```

**Comment by mgcyung** [comment]
The regex expression excludes "translate.google.com" so that proxy
goes only for "translate.google.com".

**Comment by stardiviner** [comment]
Aha, I see. Thanks, @mgcyung . I got it.
