### ISSUE TITLE
how to use in pdf-tools?

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [atykhonov/google-translate#73]
the pdf text content doesn't like any content in emacs file
you may format it that emacs can read it and then translate it
how to pass the format pdf content to this google-translate function?

**Comment by alezost** [comment]
I think that [the same issue on pdf-tools](https://github.com/politza/pdf-tools/issues/285) and [stackexchange link](https://emacs.stackexchange.com/questions/33835/how-to-use-google-translate-directly-in-pdf-tools) should have been mentioned.

**Comment by vuquangtam** [comment]
My solution for using in pdf-tools

`(defun pdf-google-translate()
  (interactive)
  (google-translate-translate
   google-translate-default-source-language
   google-translate-default-target-language
   (pdf-view-kill-ring-save)
   )
  )
(define-key pdf-view-mode-map (kbd "C-c t") 'pdf-google-translate)`

**Comment by stardiviner** [comment]
I think @vuquangtam 's solution is great. @earthIsAPrisonIfYouNotAwareItCanNotOut  What do you think? close now, if you have other thoughts, re-open issue welcome.
