### ISSUE TITLE
Failed to search TTK

### ISSUE THREAD

**Issue by djrmarques** [atykhonov/google-translate#80]
I was using google-translate for months and suddenly I started getting this error for every translation. 
I don't recall changing anything  so I don't understand why it stopped working. 

I am using version 0.11.14 on Emacs 25.2.2

Thank you!

**Comment by timHau** [comment]
Can confirm the issue 
also using version 0.11.14 on Emacs 26.1

**Comment by jajpater** [comment]
Idem, error message is: 

Contacting host: translate.google.com:443
uncompressing publicsuffix.txt.gz...done
google-translate--search-tkk: Failed to search TKK

**Comment by jajpater** [comment]
Seems to be the same issue as: https://github.com/atykhonov/google-translate/issues/52

**Comment by djrmarques** [comment]
I saw that issue but decided to open another one because that was for an older version. Should I close this so that we can all move to the older one?

**Comment by ybiquitous** [comment]
@djrmarques Thank you for opening this issue!

But I fixed this error via a great workaround in <https://github.com/atykhonov/google-translate/issues/52#issuecomment-423870290>.

Because duplicate issues confuse people who are finding a solution, could you close this issue ? 🙏

**Comment by ybiquitous** [comment]
@atykhonov Thanks! 😊

**Comment by atykhonov** [comment]
> I saw that issue but decided to open another one because that was for an older version. Should I close this so that we can all move to the older one?

This issue emerges from time to time, so even if we'll fix it now this would be a temporal fix. So there is a permanent #52 issue for that and it is not going to be closed. Anybody who runs into the issue could go there, read what happened previously, what actually happens (if happens at all) and discuss it. That issue is for all versions of `google-translate`, for old, current and any other future versions.

**Comment by rileyrg** [comment]
> Contacting host: translate.google.com:80
> uncompressing publicsuffix.txt.gz...done
> google-translate--search-tkk: Search failed: ",tkk:'"
> 

Happening to me on debian bullseye. Latest pull from melpa/straight. 

    ```
 (use-package google-translate
       :ensure t
       :init
       (when (and (string-match "0.11.17"
                              (google-translate-version))
                (>= (time-to-seconds)
                    (time-to-seconds
                     (encode-time 0 0 0 23 9 2018))))
       (defun google-translate--get-b-d1 ()
         (list 427110 1469889687))))

```
