### ISSUE TITLE
DeepL backend?

### ISSUE THREAD

**Issue by Ambrevar** [atykhonov/google-translate#87]
I know this would defeat the package name, but what about adding a https://www.deepl.com backend?

**Comment by narendraj9** [comment]
I didn't know about DeepL before this comment. DeepL API is very simple but only available for the paid subscription.

**Comment by stardiviner** [comment]
Based on it's subscription mode, It also need API for user. Not a public mode. Not a very good choise to integrate it. But still you can try to implement it as a backend for a fork. Maintainer might consider whether merge it. WDYT? @Ambrevar 
For now, let close it.
