### ISSUE TITLE
Feature request:  put last used  translation directions on top

### ISSUE THREAD

**Issue by QiangF** [atykhonov/google-translate#92]
Often user use one direction in a short period of time. So put the last used on top of google-translate-translation-directions-alist will prevent from C-n every time.

**Comment by stardiviner** [comment]
This is interesting, would you like to create PR for this feature?

**Comment by QiangF** [comment]
I really wanted to. I need to get more experienced in elisp programming.

**Comment by stardiviner** [comment]
That's ok, Elisp is not hard to learn.
