### ISSUE TITLE
google-translate-backend--emacs: Search failed

### ISSUE THREAD

**Issue by aadcg** [atykhonov/google-translate#94]
Hi,

I've been using this package for a while and I remember it was working. 
However, I'm getting the following error now (copied from `*Messages*`):

```
Contacting host: translate.google.com:80
google-translate-backend--emacs: Search failed: "

"
```

In `*google-translate-backend-debug*` I get:

```
Sun Aug 25 11:08:37 2019
("http://translate.google.com/" emacs)
-- begin --

-- end --
```

Do you have any ideas on this error?

Versions:
Ubuntu 19.04
Emacs 26.1

**Comment by ag91** [comment]
I have got the same issue.
Essentially

`(url-retrieve-synchronously "http://translate.google.com/")`

is not creating a buffer and the search for '"tkk':" is failing.
This is breaking the call:

`(google-translate-backend-retrieve
                       google-translate--tkk-url)` in google-translate-tk.el.

(Strangely enough the asynchronous version works: `(url-retrieve "http://translate.google.com/" (lambda (x) (message "Buffer: %s" (buffer-substring-no-properties (point-min) (point-max)))))` - maybe a problem of the latest version of Emacs itself?)

@aadcg can you confirm that if you change the backend method you get a new error:
for instance I get the error, condition-case: JSON readtable error: 60 if I set:
`(setq google-translate-backend-method 'curl)`

**Comment by aadcg** [comment]
Well, things started to work for me again... not sure why. And for you, @ag91 ?

**Comment by ag91** [comment]
Lol, it seems same for me...
Maybe something wrong on google side? And we disturb these nice folks of google-translate.el ;)

**Comment by aadcg** [comment]
Yes, maybe google...
At least we saw it together so none of us hallucinated! 
I'm closing this issue.

**Comment by Sbozzolo** [comment]
I am re-opening this since I am still experiencing the problem with the same error.

**Comment by aadcg** [comment]
That makes two of us. Any ideas?

**Comment by ag91** [comment]
what is your value of `google-translate-backend-method`?

**Comment by aadcg** [comment]
`emacs`. I changed to `curl` and it works for me. What about you?

**Comment by ag91** [comment]
I moved to curl as well for safety, because on another machine I could still observe the error.

**Comment by Sbozzolo** [comment]
Same here, with `emacs` fails, but with `curl` it works.

**Comment by stardiviner** [comment]
I can't reproduce this problem on my machine, can somebody provide some detailed info like Edebug.
You can check out following link to learn it if you don't know how to use Edebug.
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Edebug.html
- https://www.gnu.org/software/emacs/manual/html_node/eintr/edebug.html

**Comment by aadcg** [comment]
Everything's working for me. I'm closing this.

**Comment by tlkahn** [comment]
(setq google-translate-backend-method 'curl)
