### ISSUE TITLE
[Question] - Raw string API.

### ISSUE THREAD

**Issue by jcs090218** [atykhonov/google-translate#96]
Hi, thanks for this amazing package!

I just wonder is there a function that I could call and just return the translated text as a string? If not, do you this is possible to do from this package? What I would image would be something like.

```el
(defun google-translate--get-translated (src-lan target-lan text/sentence)
  // code here..
  )
```

Thanks.

**Comment by rynoV** [comment]
I don't think this kind of function exists at the moment, but this function should return translated text:
```lisp
(defun my-fr-to-en ()
  "Return input text translated from french to english"
  (interactive)
  (setq google-translate-output-destination 'kill-ring)
  (google-translate-query-translate)
  (current-kill 0))
```
I'm not sure how to pass the text to be translated programmatically, but it could probably be done with some elisp hackery.

**Comment by jcs090218** [comment]
Thanks! :D
