### ISSUE TITLE
question / feature request

### ISSUE THREAD

**Issue by olavfosse** [atykhonov/google-translate#97]
Hello is it possible to input a sentence and have the translation be inserted in the current buffer?

**Comment by rynoV** [comment]
When `google-translate-output-destination` is `current-buffer`, set like this:
```lisp
(setq google-translate-output-destination 'current-buffer)
```
the translations will output to the current buffer. `M-x google-translate-query-translate` should allow you to input the sentence and languages.

**Comment by f279801** [comment]
Also, the `google-translate-query-translate` alternative, `M-x google-translate-smooth-translate` will query you for the input string as well if you use the smooth UI.
In case you already have the string in the same buffer, then you can mark it and then `M-x google-translate-buffer`. Or just `M-x google-translate-buffer` if you want to translate the whole buffer.
Note that, google limit the length of the sentence/paragraph that can be translated a time.

**Comment by stardiviner** [comment]
Should this be an command for just let user change the option? WDYT?
Let's vote for this command. If you want this, please click the thumb on my reply. I will consider to add it.
